services:
  cloudpub:
    image: cloudpub/cloudpub:latest
    container_name: ${CLOUDPUB_CONTAINER}
    environment:
      - TOKEN=${CLOUDPUB_TOKEN}
      - HTTP=host.docker.internal:${NGINX_HTTP_PORT_EXT}, host.docker.internal:${WEBHOOK_PORT_EXT}
    command: run
    volumes:
      - cloudpub-config:/home/cloudpub

volumes:
  cloudpub-config: