services:
  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER}
    ports:
      - "${NGINX_HTTP_PORT_EXT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./main.conf:/etc/nginx/conf.d/main.conf:ro
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  proxy:
    external: true